### ISSUE TITLE
Navbar - FE

### ISSUE THREAD

**Issue by jamalbrowning** [jamalbrowning/forgotten-potatoes-client#15]
# User Story
As a User, I should be able to navigate across the site via a NavBar

# AC
**When** a User goes to a site there should be a Navbar at the top that is sticky.
**Then** they should be able to navigate the pages using it.
## Dev Notes
- use some sort of UI library to create the navbar

**Nav**
``` HTML
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
```
**CSS**
``` CSS
body {
  font-family: Monospace;
  font-size: 14pt;
}
blockquote {
  font-family: Arial;
  background-color: #F8EFBE;
  border-left-color: #F4B514;
}

#contactme {
  background-color: black;
  color: white;
  height: 180px;
}


#navbar {
  position: relative;
  top: 0px;
  left: 0px;
  width: 100%;
}

.top-nav {
  background-color: #671100;
}

.top-nav a {
  color: #d3e316;
}

h1.headingStatement {
  font-family: Monospace;
  font-size: 2em;
}


/* bootstrap override */

a.btn-primary:hover {
  text-decoration: none;
}

.navbar-nav li a:hover {
    background-color: #FF0000;
    border-radius: 10px;
}
.navbar-toggle .icon-bar {
  display: block;
  width: 22px;
  height: 2px;
  background-color: #cccccc;
  border-radius: 1px;
}
```
